### ISSUE TITLE
Fetch is not defined

### ISSUE THREAD

**Issue by notflip** [CodingButter-LLC/directus-migrator#11]
When running `npx directus-migrator -s development -t staging` I get the following error, this is the first time I'm using this library, followed the docs. 

This is my config 
```
const config = {
    "environments": [
        {
            "name": "development",
            "endpoint": "http://localhost:3000",
            "accessToken": "XXXXXXX"
        },
        {
            "name": "staging",
            "endpoint": "https://XXXXXXXX.cleaver.rocks",
            "accessToken": "XXXXXXX"
        }
    ]
}
 module.exports = config%  
```

This is the error

```
2023-06-18 [git:hello@miguelstevens.be] info: Migrating Schema Started
/Users/miguelstevens/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/utils/CRUD.js:48
        const response = yield fetch(url, {
                         ^

ReferenceError: fetch is not defined
    at /Users/miguelstevens/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/utils/CRUD.js:48:26
    at Generator.next (<anonymous>)
    at /Users/miguelstevens/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/utils/CRUD.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/miguelstevens/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/utils/CRUD.js:4:12)
    at CRUD (/Users/miguelstevens/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/utils/CRUD.js:45:12)
    at /Users/miguelstevens/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/migrators/schema-migration.js:69:51
    at Generator.next (<anonymous>)
    at /Users/miguelstevens/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/migrators/schema-migration.js:31:71
    at new Promise (<anonymous>)
```

**Comment by CodingButter** [comment]
I can't seem to reproduce this error

**Comment by Dominic-Preap** [comment]
I have the same issue, It seem it's required node v18 that come with global `fetch`.
