### ISSUE TITLE
export default config

### ISSUE THREAD

**Issue by co2nunes** [CodingButter-LLC/directus-migrator#9]
Hi CodingButter,

For Docker users, I think the commands should be documented and that may be the reason of this issue.
AWS EC2 Linux and latest Directus with Postgres Database

$ npx directus-migrator -init
```
.npm/_npx/2f9ed6e235e43e28/node_modules/command-line-args/dist/index.js:1202
        throw err
        ^

ALREADY_SET: Singular option already set [init=true]
    at FlagOption._set (/.npm/_npx/2f9ed6e235e43e28/node_modules/command-line-args/dist/index.js:1198:21)
    at FlagOption.set (/.npm/_npx/2f9ed6e235e43e28/node_modules/command-line-args/dist/index.js:1182:10)
    at FlagOption.set (/.npm/_npx/2f9ed6e235e43e28/node_modules/command-line-args/dist/index.js:1245:11)
    at commandLineArgs (/.npm/_npx/2f9ed6e235e43e28/node_modules/command-line-args/dist/index.js:1392:14)
    at Object.<anonymous> (/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/bin/commands.config.js:95:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  value: true,
  optionName: 'init'
}
```

$ npx directus-migrator -s development -t staging -p

/home/ec2-user/api/directus-migrator.config.js:15
export default config 
^^^^^^

```
SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/bin/cli.js:9:58)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
```

$ node -v
v18.12.1

**Comment by co2nunes** [comment]
I went ahead and changed `export default config` into `module.exports = config;` and then it crashed on:

````
$ npx directus-migrator --permissions -s development -t staging
...
2023-06-14 [unknown] info: Migrating Roles
(node:44744) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2023-06-14 [unknown] info: Retrieved Roles from development
2023-06-14 [unknown] info: Retrieved Roles from staging
2023-06-14 [unknown] info: Created: 7, Deleted: 6
2023-06-14 [unknown] info:
2023-06-14 [unknown] info: Created 7 Role/s
2023-06-14 [unknown] info:
2023-06-14 [unknown] info:
2023-06-14 [unknown] info:
2023-06-14 [unknown] info:
2023-06-14 [unknown] info:
2023-06-14 [unknown] info:
2023-06-14 [unknown] info: Migrating Roles Complete
2023-06-14 [unknown] info: Migrating Permissions
2023-06-14 [unknown] info: Created: 457, Updated: 0, Deleted: 395
/home/jorge/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/migrators/role-migration.js:121
            throw new Error(failMessage(roleResponse));
                  ^

Error: Failed to Delete roles
 false
    at /home/jorge/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/migrators/role-migration.js:121:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/jorge/.npm/_npx/2f9ed6e235e43e28/node_modules/directus-migrator/dist/migrators/role-migration.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.1
````

- Users got suspended exept me as Admin
- Users lost association with their Role
- I wasn't aware it would sync their RoleID's ( thanks!)

- Tested with Directus 10.13.0 (Docker)

Should you require more information, I'll be happy to assist you.

**Comment by co2nunes** [comment]
It worked n a fresh database but I still have to change `export default config`  for `module.exports = config;`
